version: "3"
services:

  # TODO: needs update to modern version
  #home-assistant:
  #  image: homeassistant/home-assistant
  #  volumes:
  #    - /services/home-assistant:/config
  #    - /etc/localtime:/etc/localtime:ro
  #  network_mode: "host"

  letsencrypt:
    image: linuxserver/letsencrypt
    volumes:
      - /srv/letsencrypt:/config
      - /srv/certs:/config/etc/letsencrypt
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Europe/Stockholm'
      - 'URL=jlh.name'
      - 'SUBDOMAINS=wildcard'
      - 'VALIDATION=dns'
      - 'DNSPLUGIN=cloudflare'
      - 'EMAIL=jtlex8@gmail.com'
      - 'STAGING=false'

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - 'DEFAULT_HOST=www.jlh.name'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/certs/live/jlh.name/fullchain.pem:/etc/nginx/certs/jlh.name.crt:ro
      - /srv/certs/live/jlh.name/privkey.pem:/etc/nginx/certs/jlh.name.key:ro
      - /srv/proxy_body_size.conf:/etc/nginx/conf.d/proxy_body_size.conf


  clouddb:
    image: mariadb
    volumes:
      - /srv/nextcloud-db:/var/lib/mysql
    environment:
      - 'MYSQL_RANDOM_ROOT_PASSWORD=true'
      - 'MYSQL_DATABASE=nextcloud'
      - 'MYSQL_USER=nextcloud'
      - 'MYSQL_PASSWORD=nextcloud'

  cloudredis:
    image: redis:alpine

  nextcloud:
    image: nextcloud:16.0-apache
    volumes:
      - /srv/nextcloud:/var/www/html
      - /mnt/nas:/var/www/html/data
      - /mnt/media:/mnt/media
    links:
      - clouddb
      - cloudredis
    environment:
      - 'MYSQL_DATABASE=nextcloud'
      - 'MYSQL_USER=nextcloud'
      - 'MYSQL_PASSWORD=nextcloud'

      - 'MYSQL_HOST=clouddb:3306'
      - 'REDIS_HOST=cloudredis'

      - 'VIRTUAL_HOST=cloud.jlh.name'


  unifi:
    image: goofball222/unifi
    network_mode: "host"
    ports:
      - "3478:3478/udp"
      - "6789:6789"
      - "8080:8080"
      - "8443:8443"
      - "8880:8880"
      - "8843:8843"
      - "10001:10001/udp"
    volumes:
      - /srv/unifi/cert:/usr/lib/unifi/cert
      - /srv/unifi/data:/usr/lib/unifi/data
      - /srv/unifi/logs:/usr/lib/unifi/logs


  website:
    image: nginx:alpine
    environment:
      - 'VIRTUAL_HOST=www.jlh.name'
    volumes:
      - /srv/website/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/website/www:/usr/share/nginx/html:ro


  wikidb:
    image: mongo
    expose:
      - '27017'
    command: '--smallfiles --bind_ip wikidb'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - /srv/wiki/mongo:/data/db

  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    environment:
      - 'WIKI_ADMIN_EMAIL=admin@example.com'
      - 'VIRTUAL_HOST=wiki.jlh.name'
      - 'VIRTUAL_PORT=3000'
      - 'NETWORK_ACCESS=internal'
    volumes:
      - /srv/wiki/config.yml:/var/wiki/config.yml
      - /srv/wiki/id_rsa:/var/wiki/id_rsa
